name = "file1"
main = "src/worker.js"
compatibility_date = "2023-07-06"

# # KV Namespace binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/kv
[[kv_namespaces]]
binding = "ENV"
id = "31a442e25dd6448eb650331916f64534"
preview_id = "cd438d0e1a4a4ee6915cfad327e86944"
